//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavBankasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Choice = new HashSet<Choice>();
            this.TestXQuestion = new HashSet<TestXQuestion>();
        }
    
        public int QuestionId { get; set; }
        public Nullable<int> QuestionCategoryId { get; set; }
        public string QuestionType { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> ExhibitId { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Choice> Choice { get; set; }
        public virtual Exhibit Exhibit { get; set; }
        public virtual QuestionCategory QuestionCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestXQuestion> TestXQuestion { get; set; }
    }
}
