//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavBankasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.QuestionXDuration = new HashSet<QuestionXDuration>();
            this.TestXPaper = new HashSet<TestXPaper>();
        }
    
        public int RegistrationId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> TokenExpireTime { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionXDuration> QuestionXDuration { get; set; }
        public virtual Student Student { get; set; }
        public virtual Test Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestXPaper> TestXPaper { get; set; }
    }
}
